# Generated by Django 5.0.1 on 2025-09-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_newuser_outlet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="username",
        ),
    ]
