# Generated by Django 5.0.1 on 2025-09-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_newuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="username",
            field=models.CharField(default="anonymous", max_length=255, unique=True),
        ),
    ]
