# Generated by Django 5.0.1 on 2025-09-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employees_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="gender",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
