# Generated by Django 5.0.1 on 2025-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employees_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
    ]
