# Generated by Django 5.0.1 on 2025-09-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employees_gender"),
        ("outlets", "0002_alter_outlet_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="outlets.outlet",
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="perm_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="role",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("Branch Manager", "Branch Manager"),
                    ("Staff head", "Staff head"),
                    ("Employee", "Employee"),
                    ("Accountant", "Accountant"),
                    ("Staff", "Staff"),
                ],
                default="Employee",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="temp_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
