# Generated by Django 5.0.1 on 2025-08-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
