# Generated by Django 5.0.1 on 2025-09-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_service_updated_at_outletserviceprice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OutletServicePrice",
        ),
    ]
