# Generated by Django 5.0.1 on 2025-08-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outlets/'),
        ),
    ]
