# Generated by Django 5.0.1 on 2025-09-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0002_alter_outlet_image"),
        ("service", "0004_delete_outletserviceprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutletServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="outlets.outlet"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.service",
                    ),
                ),
            ],
            options={
                "db_table": "db_outlet_service_prices",
                "unique_together": {("outlet", "service")},
            },
        ),
    ]
