# Generated by Django 5.0.1 on 2025-10-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0003_outletserviceprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutletSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("total_seats", models.PositiveIntegerField(default=5)),
                ("available_seats", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="outlets.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "db_outlet_slots",
                "ordering": ["start_time"],
            },
        ),
    ]
