# Generated by Django 5.0.1 on 2025-10-10 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0004_outletslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlet",
            name="closing_time",
            field=models.TimeField(
                default=datetime.time(18, 0), help_text="Default closing time"
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="is_closed",
            field=models.BooleanField(
                default=False, help_text="If checked, outlet is closed for bookings"
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="opening_time",
            field=models.TimeField(
                default=datetime.time(10, 0), help_text="Default opening time"
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="total_slots",
            field=models.PositiveIntegerField(
                default=6, help_text="Maximum concurrent bookings (default 6)"
            ),
        ),
        migrations.DeleteModel(
            name="OutletSlot",
        ),
    ]
