# Generated by Django 5.0.1 on 2025-10-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0005_outlet_closing_time_outlet_is_closed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlet",
            name="is_closed",
            field=models.BooleanField(
                default=False, help_text="If true, outlet is closed for bookings"
            ),
        ),
    ]
