# Generated by Django 5.0.1 on 2025-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_booking_service_booking_status_bookingservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="esewa_tid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
